seed:
device: cuda
agent_name: dmlp

#eval
num_eval_ep: 10
num_eval_len:

# env
env_name: 
dataset_name: pointmaze-medium-v0
remote_data: False
num_workers: 4
render: False

#train
num_updates_per_iter: 40000
max_train_iters: 25         #25 x 40000 -> 1000000 transition batches

augment_data: True
augment_prob: 0.5
nclusters: 40
dataset_config: {only_goal_aug: True}
batch_size: 256
lr: 1e-3

#logging
log_dir: logs/
log_time: ${now:%Y%m%d}_${now:%H%M%S}
save_path:
wandb_log: True
wandb_entity: yluo
wandb_run_name:
wandb_group_name: 
wandb_dir:

#saving
save_snapshot: True
save_snapshot_interval: 25

#hydra
hydra:
  run:
    dir: ${log_dir}/${dataset_name}/${hydra:job.config_name}/${now:%Y%m%d}_${now:%H%M%S}
  job:
    chdir: False